# Generated by Django 4.2.2 on 2023-06-12 20:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='A tournament', max_length=100, verbose_name='name')),
                ('tour_id', models.CharField(max_length=20, unique=True, verbose_name='tour_id')),
                ('alias', models.CharField(max_length=20, unique=True, verbose_name='alias')),
                ('tournament_type', models.CharField(choices=[('swiss', 'Swiss'), ('single', 'Single Elimination'), ('swiss_single', 'Swiss plus Single Elimination')], max_length=100, verbose_name='type')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2014, 10, 6, 13, 0), verbose_name='start time')),
                ('description', models.TextField(default='', verbose_name='description')),
                ('status', models.SmallIntegerField(default=-2, verbose_name='status')),
                ('remarks', models.TextField(default='{}')),
                ('admins', models.ManyToManyField(to='accounts.playeruser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_number', models.SmallIntegerField(verbose_name='turn number')),
                ('standings', models.TextField(verbose_name='standings')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
                ('status', models.SmallIntegerField(default=0, verbose_name='status')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmtour.tournament')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('playerid', models.SmallIntegerField()),
                ('wins', models.SmallIntegerField(default=0)),
                ('loses', models.SmallIntegerField(default=0)),
                ('ties', models.SmallIntegerField(default=0)),
                ('byes', models.SmallIntegerField(default=0)),
                ('standing', models.SmallIntegerField(default=0)),
                ('late', models.BooleanField(default=False)),
                ('eliminated', models.BooleanField(default=False)),
                ('exited', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('foes', models.ManyToManyField(to='pmtour.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmtour.tournament')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.playeruser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=0, verbose_name='status')),
                ('results', models.TextField(default='', verbose_name='results')),
                ('time', models.DateTimeField(null=True, verbose_name='time')),
                ('table_id', models.SmallIntegerField(verbose_name='table id')),
                ('player_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_a_log', to='pmtour.player')),
                ('player_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_b_log', to='pmtour.player')),
                ('turn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pmtour.turn')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
