# Generated by Django 4.2.2 on 2023-06-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmtour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bye_rounds',
            field=models.SmallIntegerField(default=0),
        ),
    ]
