name: Build executables

on: [push]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cp ./mysite/settings_default.py ./mysite/settings.py
      - name: Use PyInstaller to pack
        working-directory: scripts
        run: |
          pip install pyinstaller==4.4
          ./patch.sh
          ./dist.sh
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pmtour-${{ matrix.os }}
          path: ./dist/pmtour.zip
